library(tidyverse)
library(data.table)
library(mergingTools)
exp <- read.csv("t2080-analysis/Data/experiments/w-1-1000.csv")
a <- merge_hems(data = exp, anchor_hem = "PROCESSOR_CYCLES", n_runs = 1000, n_subexp = 3, n_pmcs = 6, processed = F)
write.csv(a, "test_w1.csv", row.names = F)


library(devtools)
library(roxygen2)
setwd("mergingTools/")
document()
check()
setwd("..")
install("mergingTools/")
